apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env: 
        # Matches the secret we created at the command line.
        - name: CONNECTION_REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: url
        ports:
        - containerPort: 3000