name: Test Quickstarts

on:
  workflow_dispatch:
  push:
    branches:
      - v*.*
      - edge
    paths:
      - 'quickstarts/**'
      - 'reference-apps/**'
      - '.github/workflows/**'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - v*.*
      - edge

jobs:
  build:
    name: Deploy quickstarts to local environment
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: demo
            app: demo
            path: ./demo/app.bicep
            args: --application demo
          - name: dapr
            app: dapr-quickstart
            path: ./quickstarts/dapr/dapr.bicep
          - name: environment-variables
            app: myapp
            path: ./quickstarts/environment-variables/app.bicep
          - name: volumes
            app: myapp
            path: ./quickstarts/volumes/app.bicep
          - name: eshop
            app: eshop
            path: ./reference-apps/eshop/iac/eshop.bicep
    env:
      BRANCH: ${{ github.base_ref || github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: az CLI login
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_SP_TESTS_APPID }} \
            --password ${{ secrets.AZURE_SP_TESTS_PASSWORD }} \
            --tenant ${{ secrets.AZURE_SP_TESTS_TENANTID }}
      - name: Download k3d
        run:  wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
      - name: Download rad
        run: |
           echo "Downloading rad with branch: ${BRANCH}"
           if [ "$BRANCH" = "edge" ]; then
             wget -q "https://get.radapp.dev/tools/rad/install.sh" -O - | /bin/bash -s edge
           else
             wget -q "https://get.radapp.dev/tools/rad/install.sh" -O - | /bin/bash
           fi
      - name: Init local environment
        run: |
          k3d cluster create -p "8081:80@loadbalancer" --k3s-arg "--disable=traefik@server:0"
          rad env init kubernetes --public-endpoint-override 'localhost:8081' -e test
          helm repo add dapr https://dapr.github.io/helm-charts/
          helm install dapr dapr/dapr --version=1.6 --namespace dapr-system --create-namespace --wait
      - name: Deploy app
        run:  rad deploy ${{ matrix.path }} ${{ matrix.args }}
      - name: Delete app
        run:  rad app delete ${{ matrix.app }} -y
